### ISSUE TITLE
Error messages not being displayed

### ISSUE THREAD

**Issue by vuld0** [CodeRoyale/frontend#69]
No error messages are being displayed when start competition is clicked when room doesn't meet requirements 

![Screenshot from 2021-05-23 19-41-35](https://user-images.githubusercontent.com/42476557/119264010-0a5f3b80-bbff-11eb-81dd-1e9184a7ae39.png)

As you can see in the image shown above.
There are two users in the room and both of them are in the same team though there must be minimum 1 user in the other team as well. So some error should be shown

![Screenshot from 2021-05-23 19-46-01](https://user-images.githubusercontent.com/42476557/119264149-8bb6ce00-bbff-11eb-996b-a5f884c99f7e.png)

**Comment by Rec0iL99** [comment]
@vuld0 please provide the room specification values you gave when you created the room, specifically "Maximum Members in a Team".

**Comment by vuld0** [comment]
@Rec0iL99, the value of "Maximum Members in a team" was given as "1".
