### ISSUE TITLE
An alert message should pop-up when user tries to go "back"

### ISSUE THREAD

**Issue by vuld0** [CodeRoyale/frontend#70]
Close the room when user presses the "back" button in the browser.

**Comment by Rec0iL99** [comment]
This is not a valid issue, since the room should only be closed when the admin of the room clicks on the "Close Room" button.

**Comment by Rec0iL99** [comment]
@vuld0 are you trying to say that the user needs to have the option to rejoin the room, if they exit the room by mistake? 

Rejoining a room is not yet implemented 😄!

**Comment by vuld0** [comment]
We can at least provide an alert message or something.

Like the pop up "Stay on the page or leave the page"

**Comment by Rec0iL99** [comment]
> We can at least provide an alert message or something.
> 
> Like the pop up "Stay on the page or leave the page"

Yes, we could do that.

But also a better solution in my opinion would be to allow the user to rejoin the room, if they exit the room by mistake
